---
- name: Deploiement d'Apache via Docker
  hosts: prod
  become: yes
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: installation des dependances
      yum:
        name: python-docker-py
        state: present
        update_cache: yes
    - name: installation de wget et git avec les loops
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - wget
      when: ansible_facts['distribution'] == "CentOS" 
  tasks:
    - name: copy index.html template
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: creation du container
      docker_container:
        name: webapp
        image: httpd
        state: started
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
